version: '3'
services:
  bbc:
    image: bbc-monitor
    build: .
    volumes:
      - ./bbc.py:/bbc.py
      - ./main.py:/main.py
    environment:
      TZ: Asia/Saigon
      LINK: https://www.youtube.com/user/BBCVietnamese/videos 
